#!/usr/bin/env python3

from PyQt5 import QtCore, QtGui, QtWidgets
from time import strftime

class Ui_Form(object):
    def setupUi(self, Form):
        #Setup_FORM        
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.setEnabled(True)
        Form.resize(660, 380)
        Form.setFixedSize(Form.size())
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        ################################################################
        #Setup_LABEL_TOP
        self.hLayout_TOP = QtWidgets.QHBoxLayout()
        self.hLayout_TOP.setObjectName("hLayout_TOP")
        self.label_top = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_top.sizePolicy().hasHeightForWidth())
        self.label_top.setSizePolicy(sizePolicy)
        self.label_top.setObjectName("label_top")
        self.hLayout_TOP.addWidget(self.label_top)
        ################################################################
        #setup_INPUTs
        self.vLayout_INPUT = QtWidgets.QVBoxLayout()
        self.vLayout_INPUT.setObjectName("vLayout_INPUT")
        self.lineEditAPIKEY = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditAPIKEY.sizePolicy().hasHeightForWidth())
        self.lineEditAPIKEY.setSizePolicy(sizePolicy)
        self.lineEditAPIKEY.setText("")
        self.lineEditAPIKEY.setObjectName("lineEditAPIKEY")
        self.vLayout_INPUT.addWidget(self.lineEditAPIKEY)
        self.hLayout_INPUT = QtWidgets.QHBoxLayout()
        self.hLayout_INPUT.setObjectName("hLayout_INPUT")
        self.lineEditCity = QtWidgets.QLineEdit(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditCity.sizePolicy().hasHeightForWidth())
        self.lineEditCity.setSizePolicy(sizePolicy)
        self.lineEditCity.setText("")
        self.lineEditCity.setObjectName("lineEditCity")
        self.hLayout_INPUT.addWidget(self.lineEditCity)
        ################################################################
        #setup_PUSHBUTTON
        self.pushButton = QtWidgets.QPushButton(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setStyleSheet("font: 75 16pt \"Liberation Sans\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(55, 188, 62);")
        self.pushButton.setObjectName("pushButton")
        self.hLayout_INPUT.addWidget(self.pushButton)
        self.vLayout_INPUT.addLayout(self.hLayout_INPUT)
        self.hLayout_TOP.addLayout(self.vLayout_INPUT)
        ################################################################
        #setup_LABEL_DATE
        self.label_date = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_date.sizePolicy().hasHeightForWidth())
        self.label_date.setSizePolicy(sizePolicy)
        self.label_date.setFrameShape(QtWidgets.QFrame.Box)
        self.label_date.setAlignment(QtCore.Qt.AlignCenter)
        self.label_date.setObjectName("label_date")
        self.hLayout_TOP.addWidget(self.label_date)
        ################################################################
        #setup_LABEL_TIME
        self.label_time = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_time.sizePolicy().hasHeightForWidth())
        self.label_time.setSizePolicy(sizePolicy)
        self.label_time.setFrameShape(QtWidgets.QFrame.Box)
        self.label_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time.setObjectName("label_time")
        self.hLayout_TOP.addWidget(self.label_time)
        self.gridLayout.addLayout(self.hLayout_TOP, 0, 0, 1, 1)
        ################################################################
        #setup_LABEL_CITY
        self.label_city = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_city.sizePolicy().hasHeightForWidth())
        self.label_city.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_city.setFont(font)
        self.label_city.setFrameShape(QtWidgets.QFrame.Box)
        self.label_city.setTextFormat(QtCore.Qt.AutoText)
        self.label_city.setAlignment(QtCore.Qt.AlignCenter)
        self.label_city.setObjectName("label_city")
        self.gridLayout.addWidget(self.label_city, 1, 0, 1, 1)
        ################################################################
        #Setup_LABEL_DAYs
        self.hLayout_DAY = QtWidgets.QHBoxLayout()
        self.hLayout_DAY.setObjectName("hLayout_DAY")
        self.label_empty = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_empty.sizePolicy().hasHeightForWidth())
        self.label_empty.setSizePolicy(sizePolicy)
        self.label_empty.setText("")
        self.label_empty.setObjectName("label_empty")
        self.hLayout_DAY.addWidget(self.label_empty)
        self.label_day_1 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_day_1.sizePolicy().hasHeightForWidth())
        self.label_day_1.setSizePolicy(sizePolicy)
        self.label_day_1.setObjectName("label_day_1")
        self.hLayout_DAY.addWidget(self.label_day_1)
        self.label_day_2 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_day_2.sizePolicy().hasHeightForWidth())
        self.label_day_2.setSizePolicy(sizePolicy)
        self.label_day_2.setObjectName("label_day_2")
        self.hLayout_DAY.addWidget(self.label_day_2)
        self.label_day_3 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_day_3.sizePolicy().hasHeightForWidth())
        self.label_day_3.setSizePolicy(sizePolicy)
        self.label_day_3.setObjectName("label_day_3")
        self.hLayout_DAY.addWidget(self.label_day_3)
        self.label_day_4 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_day_4.sizePolicy().hasHeightForWidth())
        self.label_day_4.setSizePolicy(sizePolicy)
        self.label_day_4.setObjectName("label_day_4")
        self.hLayout_DAY.addWidget(self.label_day_4)
        self.label_day_5 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_day_5.sizePolicy().hasHeightForWidth())
        self.label_day_5.setSizePolicy(sizePolicy)
        self.label_day_5.setObjectName("label_day_5")
        self.hLayout_DAY.addWidget(self.label_day_5)
        self.gridLayout.addLayout(self.hLayout_DAY, 2, 0, 1, 1)
        ################################################################
        #setup_LABEL_ICONs
        self.hLayout_ICON = QtWidgets.QHBoxLayout()
        self.hLayout_ICON.setObjectName("hLayout_ICON")
        self.label_empty2 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_empty2.sizePolicy().hasHeightForWidth())
        self.label_empty2.setSizePolicy(sizePolicy)
        self.label_empty2.setMaximumSize(QtCore.QSize(100, 100))
        self.label_empty2.setText("")
        self.label_empty2.setObjectName("label_empty2")
        self.hLayout_ICON.addWidget(self.label_empty2)
        self.label_icon1 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_icon1.sizePolicy().hasHeightForWidth())
        self.label_icon1.setSizePolicy(sizePolicy)
        self.label_icon1.setMaximumSize(QtCore.QSize(100, 94))
        self.label_icon1.setText("")
        self.label_icon1.setPixmap(QtGui.QPixmap("icons/7.png"))
        self.label_icon1.setScaledContents(True)
        self.label_icon1.setObjectName("label_icon1")
        self.hLayout_ICON.addWidget(self.label_icon1)
        self.label_icon2 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_icon2.sizePolicy().hasHeightForWidth())
        self.label_icon2.setSizePolicy(sizePolicy)
        self.label_icon2.setMaximumSize(QtCore.QSize(100, 94))
        self.label_icon2.setText("")
        self.label_icon2.setPixmap(QtGui.QPixmap("icons/1.png"))
        self.label_icon2.setScaledContents(True)
        self.label_icon2.setObjectName("label_icon2")
        self.hLayout_ICON.addWidget(self.label_icon2)
        self.label_icon3 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_icon3.sizePolicy().hasHeightForWidth())
        self.label_icon3.setSizePolicy(sizePolicy)
        self.label_icon3.setMaximumSize(QtCore.QSize(100, 94))
        self.label_icon3.setText("")
        self.label_icon3.setPixmap(QtGui.QPixmap("icons/2.png"))
        self.label_icon3.setScaledContents(True)
        self.label_icon3.setObjectName("label_icon3")
        self.hLayout_ICON.addWidget(self.label_icon3)
        self.label_icon4 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_icon4.sizePolicy().hasHeightForWidth())
        self.label_icon4.setSizePolicy(sizePolicy)
        self.label_icon4.setMaximumSize(QtCore.QSize(100, 94))
        self.label_icon4.setText("")
        self.label_icon4.setPixmap(QtGui.QPixmap("icons/11.png"))
        self.label_icon4.setScaledContents(True)
        self.label_icon4.setObjectName("label_icon4")
        self.hLayout_ICON.addWidget(self.label_icon4)
        self.label_icon5 = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_icon5.sizePolicy().hasHeightForWidth())
        self.label_icon5.setSizePolicy(sizePolicy)
        self.label_icon5.setMaximumSize(QtCore.QSize(100, 94))
        self.label_icon5.setText("")
        self.label_icon5.setPixmap(QtGui.QPixmap("icons/12.png"))
        self.label_icon5.setScaledContents(True)
        self.label_icon5.setObjectName("label_icon5")
        self.hLayout_ICON.addWidget(self.label_icon5)
        self.gridLayout.addLayout(self.hLayout_ICON, 3, 0, 1, 1)
        ################################################################
        #setup_LABEL_WEAs
        self.hLayout_WEA = QtWidgets.QHBoxLayout()
        self.hLayout_WEA.setObjectName("hLayout_WEA")
        self.vLayout_main = QtWidgets.QVBoxLayout()
        self.vLayout_main.setObjectName("vLayout_main")
        self.label_cond = QtWidgets.QLabel(Form)
        self.label_cond.setObjectName("label_cond")
        self.vLayout_main.addWidget(self.label_cond)
        self.label_temp = QtWidgets.QLabel(Form)
        self.label_temp.setObjectName("label_temp")
        self.vLayout_main.addWidget(self.label_temp)
        self.label_humidity = QtWidgets.QLabel(Form)
        self.label_humidity.setObjectName("label_humidity")
        self.vLayout_main.addWidget(self.label_humidity)
        self.label_wind = QtWidgets.QLabel(Form)
        self.label_wind.setObjectName("label_wind")
        self.vLayout_main.addWidget(self.label_wind)
        self.hLayout_WEA.addLayout(self.vLayout_main)
        self.vLayout_day1 = QtWidgets.QVBoxLayout()
        self.vLayout_day1.setObjectName("vLayout_day1")
        self.label_cond_2 = QtWidgets.QLabel(Form)
        self.label_cond_2.setObjectName("label_cond_2")
        self.vLayout_day1.addWidget(self.label_cond_2)
        self.label_temp_2 = QtWidgets.QLabel(Form)
        self.label_temp_2.setObjectName("label_temp_2")
        self.vLayout_day1.addWidget(self.label_temp_2)
        self.label_humidity_2 = QtWidgets.QLabel(Form)
        self.label_humidity_2.setObjectName("label_humidity_2")
        self.vLayout_day1.addWidget(self.label_humidity_2)
        self.label_wind_2 = QtWidgets.QLabel(Form)
        self.label_wind_2.setObjectName("label_wind_2")
        self.vLayout_day1.addWidget(self.label_wind_2)
        self.hLayout_WEA.addLayout(self.vLayout_day1)
        self.vLayout_day2 = QtWidgets.QVBoxLayout()
        self.vLayout_day2.setObjectName("vLayout_day2")
        self.label_cond_3 = QtWidgets.QLabel(Form)
        self.label_cond_3.setObjectName("label_cond_3")
        self.vLayout_day2.addWidget(self.label_cond_3)
        self.label_temp_3 = QtWidgets.QLabel(Form)
        self.label_temp_3.setObjectName("label_temp_3")
        self.vLayout_day2.addWidget(self.label_temp_3)
        self.label_humidity_3 = QtWidgets.QLabel(Form)
        self.label_humidity_3.setObjectName("label_humidity_3")
        self.vLayout_day2.addWidget(self.label_humidity_3)
        self.label_wind_3 = QtWidgets.QLabel(Form)
        self.label_wind_3.setObjectName("label_wind_3")
        self.vLayout_day2.addWidget(self.label_wind_3)
        self.hLayout_WEA.addLayout(self.vLayout_day2)
        self.vLayout_day3 = QtWidgets.QVBoxLayout()
        self.vLayout_day3.setObjectName("vLayout_day3")
        self.label_cond_4 = QtWidgets.QLabel(Form)
        self.label_cond_4.setObjectName("label_cond_4")
        self.vLayout_day3.addWidget(self.label_cond_4)
        self.label_temp_4 = QtWidgets.QLabel(Form)
        self.label_temp_4.setObjectName("label_temp_4")
        self.vLayout_day3.addWidget(self.label_temp_4)
        self.label_humidity_4 = QtWidgets.QLabel(Form)
        self.label_humidity_4.setObjectName("label_humidity_4")
        self.vLayout_day3.addWidget(self.label_humidity_4)
        self.label_wind_4 = QtWidgets.QLabel(Form)
        self.label_wind_4.setObjectName("label_wind_4")
        self.vLayout_day3.addWidget(self.label_wind_4)
        self.hLayout_WEA.addLayout(self.vLayout_day3)
        self.vLayout_day4 = QtWidgets.QVBoxLayout()
        self.vLayout_day4.setObjectName("vLayout_day4")
        self.label_cond_5 = QtWidgets.QLabel(Form)
        self.label_cond_5.setObjectName("label_cond_5")
        self.vLayout_day4.addWidget(self.label_cond_5)
        self.label_temp_5 = QtWidgets.QLabel(Form)
        self.label_temp_5.setObjectName("label_temp_5")
        self.vLayout_day4.addWidget(self.label_temp_5)
        self.label_humidity_5 = QtWidgets.QLabel(Form)
        self.label_humidity_5.setObjectName("label_humidity_5")
        self.vLayout_day4.addWidget(self.label_humidity_5)
        self.label_wind_5 = QtWidgets.QLabel(Form)
        self.label_wind_5.setObjectName("label_wind_5")
        self.vLayout_day4.addWidget(self.label_wind_5)
        self.hLayout_WEA.addLayout(self.vLayout_day4)
        self.vLayout_day5 = QtWidgets.QVBoxLayout()
        self.vLayout_day5.setObjectName("vLayout_day5")
        self.label_cond_6 = QtWidgets.QLabel(Form)
        self.label_cond_6.setObjectName("label_cond_6")
        self.vLayout_day5.addWidget(self.label_cond_6)
        self.label_temp_6 = QtWidgets.QLabel(Form)
        self.label_temp_6.setObjectName("label_temp_6")
        self.vLayout_day5.addWidget(self.label_temp_6)
        self.label_humidity_6 = QtWidgets.QLabel(Form)
        self.label_humidity_6.setObjectName("label_humidity_6")
        self.vLayout_day5.addWidget(self.label_humidity_6)
        self.label_wind_6 = QtWidgets.QLabel(Form)
        self.label_wind_6.setObjectName("label_wind_6")
        self.vLayout_day5.addWidget(self.label_wind_6)
        self.hLayout_WEA.addLayout(self.vLayout_day5)
        self.gridLayout.addLayout(self.hLayout_WEA, 4, 0, 1, 1)
        ################################################################
        #setup_LABEL_COPYRIGHT
        self.label_copyright = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_copyright.sizePolicy().hasHeightForWidth())
        self.label_copyright.setSizePolicy(sizePolicy)
        self.label_copyright.setScaledContents(False)
        self.label_copyright.setWordWrap(False)
        self.label_copyright.setObjectName("label_copyright")
        self.gridLayout.addWidget(self.label_copyright, 5, 0, 1, 1)
        self.label_city.raise_()
        self.label_copyright.raise_()
        ######################
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(self.Time)
        self.timer.start(1000)
        ######################
        self.retranslateUi(Form)
        self.reLabelDAYs()
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "brksnn_weather"))
        self.label_top.setText(_translate("Form", "Enter a valid API-KEY:\n"
                                                  "Enter a CITY ID or Name:\n"
                                                  "from openweathermap.org"))
        self.pushButton.setText(_translate("Form", "GO"))
        #Label_Date&Time
        self.label_date.setText(strftime("%d"+"/"+"%m"+"/"+"%Y"))
        self.label_time.setText(strftime("%H"+":"+"%M"+":"+"%S"))
        #Label_City
        self.label_city.setText(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt; font-weight:600; font-style:italic;\">Istanbul, TR</span></p></body></html>"))
        #Label_set_WEA
        #Label_Main
        self.label_cond.setText(_translate("Form", "Condition"))
        self.label_temp.setText(_translate("Form", "Temp °C"))
        self.label_humidity.setText(_translate("Form", "Humidity (%)"))
        self.label_wind.setText(_translate("Form", "Wind Speed (m/s)"))
        #Label_Day1
        self.label_cond_2.setText(_translate("Form", "Condition"))
        self.label_cond_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_temp_2.setText(_translate("Form", "Temp"))
        self.label_temp_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_humidity_2.setText(_translate("Form", "Humidity"))
        self.label_humidity_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_wind_2.setText(_translate("Form", "Wind"))
        self.label_wind_2.setAlignment(QtCore.Qt.AlignCenter)
        #Label_Day2
        self.label_cond_3.setText(_translate("Form", "Condition"))
        self.label_cond_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_temp_3.setText(_translate("Form", "Temp"))
        self.label_temp_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_humidity_3.setText(_translate("Form", "Humidity"))
        self.label_humidity_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_wind_3.setText(_translate("Form", "Wind"))
        self.label_wind_3.setAlignment(QtCore.Qt.AlignCenter)
        #Label_Day3
        self.label_cond_4.setText(_translate("Form", "Condition"))
        self.label_cond_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_temp_4.setText(_translate("Form", "Temp"))
        self.label_temp_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_humidity_4.setText(_translate("Form", "Humidity"))
        self.label_humidity_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_wind_4.setText(_translate("Form", "Wind"))
        self.label_wind_4.setAlignment(QtCore.Qt.AlignCenter)
        #Label_Day4
        self.label_cond_5.setText(_translate("Form", "Condition"))
        self.label_cond_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_temp_5.setText(_translate("Form", "Temp"))
        self.label_temp_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_humidity_5.setText(_translate("Form", "Humidity"))
        self.label_humidity_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_wind_5.setText(_translate("Form", "Wind"))
        self.label_wind_5.setAlignment(QtCore.Qt.AlignCenter)
        #Label_Day5
        self.label_cond_6.setText(_translate("Form", "Condition"))
        self.label_cond_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_temp_6.setText(_translate("Form", "Temp"))
        self.label_temp_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_humidity_6.setText(_translate("Form", "Humidity"))
        self.label_humidity_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_wind_6.setText(_translate("Form", "Wind"))
        self.label_wind_6.setAlignment(QtCore.Qt.AlignCenter)
        #Label_CopyRight
        self.label_copyright.setText(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600; font-style:italic;\">© Burak Sunan </span></p></body></html>"))

    def Time(self):
        self.label_date.setText(strftime("%d"+"/"+"%m"+"/"+"%Y"))
        self.label_time.setText(strftime("%H"+":"+"%M"+":"+"%S"))
        
    def reLabelDAYs(self):
        _translate = QtCore.QCoreApplication.translate
        d = int(strftime("%d"))
        s1 = "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">"
        s2 = "</span></p></body></html>"
        d1 = strftime(s1+"%b "+str(d)+s2)
        d2 = strftime(s1+"%b "+str(d+1)+s2)
        d3 = strftime(s1+"%b "+str(d+2)+s2)
        d4 = strftime(s1+"%b "+str(d+3)+s2)
        d5 = strftime(s1+"%b "+str(d+4)+s2)
        self.label_day_1.setText(_translate("Form",d1))
        self.label_day_2.setText(_translate("Form",d2))
        self.label_day_3.setText(_translate("Form",d3))
        self.label_day_4.setText(_translate("Form",d4))
        self.label_day_5.setText(_translate("Form",d5))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
